### PR TITLE
Address UX Comments

### PR DESCRIPTION
**Pull request by Jdubrick**
This PR aims to address the comments made on the MIRO board regarding the Tech Docs on the Model Catalog. Additionally since I removed the table of contents I had to update the first page shown to `index.md` so I updated the guides to reflect that. 

cc @MariaLeonova

Since there would be a lot of screenshots and it isn't on the live cluster I recorded a video going over each page for reference.

https://drive.google.com/file/d/13XL8q3XDo2xfXbnXsiGGfwrizsTP1hpT/view?usp=sharing

### CODE REVIEW

**Comment by MariaLeonova** [comment]
@Jdubrick thank you for introducing these changes - the text formatting is so much better as a result. It will make it easier to  read for the users and they will be able to find the information they are looking for at a glance.

**Comment by Jdubrick** [comment]
Awesome thank you @MariaLeonova ! @johnmcollier @thepetk if you have time for quick review since it's been signed off on I appreciate it greatly :)

**Review by johnmcollier — APPROVED** [review]
Looks good from my end

**Review by thepetk — COMMENTED** [review]
late in the party :cry: but looks good to me too!

**Pull request merged**
